# ____             _              _             #
#|  _ \  ___  ___ | |_  __ _ _ __| |_  ___ _ __ #
#| |_) |/ _ \/ __|| __|/ _` | '__| __|/ _ \ '__|#
#|  __/|  __/\__ \| |_| (_| | |  | |_|  __/ |   #
#|_|\_\ \___ |___/ \__|\__,_|_|   \__|\___|_|   #

#Contact with Autors:
#
#catfishua(VasilModerator)
#VK: vk.com/catfishua
#FB: facebook.com/catf1shua
#DISCORD: ЗОВУТ НАСТЯ#5934
#TWITTER: twitter.com/VasilModerator
#YOUTUBE: www.youtube.com/channel/UCCNul-65sVqMGLBF8Z8fCqw
#
#Butukay
#VK: vk.com/butukay
#DISCORD: Butukay#9999

restart-message:
  - '§6Сервер перезагружается'

time: 120 #IN MINUTES
kick-message: 'Север перезагружается'
sound: 'ENTITY_EXPERIENCE_ORB_PICKUP'

chat-msgs:
  restart: "Вы выполнили комманду рестарта, ожидайте"
  no-perm: "Вы не явяетесь администратором"


log-msgs:
  default-config-saved: "Конфиг не найден! Создаю новый конфиг."
  restart: "§aСохраняем, выключаем"
